name: Github Action Init
run-name: ${{ github.actor }} testing
on: [push]
jobs:
  express-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - run: cd tests/express
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test
